# Generated by Django 4.2.18 on 2025-01-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('zelle', 'Zelle'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash')], max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction ID')),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='proof of payment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
